// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'http.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

@freezed
sealed class RhttpError with _$RhttpError implements FrbException {
  const RhttpError._();

  const factory RhttpError.rhttpCancelError() = RhttpError_RhttpCancelError;
  const factory RhttpError.rhttpTimeoutError() = RhttpError_RhttpTimeoutError;
  const factory RhttpError.rhttpRedirectError() = RhttpError_RhttpRedirectError;
  const factory RhttpError.rhttpStatusCodeError(
    int field0,
    List<(String, String)> field1,
    HttpResponseBody field2,
  ) = RhttpError_RhttpStatusCodeError;
  const factory RhttpError.rhttpInvalidCertificateError(
    String field0,
  ) = RhttpError_RhttpInvalidCertificateError;
  const factory RhttpError.rhttpConnectionError(
    String field0,
  ) = RhttpError_RhttpConnectionError;
  const factory RhttpError.rhttpUnknownError(
    String field0,
  ) = RhttpError_RhttpUnknownError;
  const factory RhttpError.rhttpWebSocketError(
    WebSocketError field0,
  ) = RhttpError_RhttpWebSocketError;
}

@freezed
sealed class WebSocketError with _$WebSocketError {
  const WebSocketError._();

  /// HTTP upgrade failed (not a 101 response, bad headers, and so on).
  const factory WebSocketError.handshakeFailed({
    required int status,
    String? reason,
  }) = WebSocketError_HandshakeFailed;

  /// WebSocket protocol violation after upgrade.
  const factory WebSocketError.protocolError({
    required String message,
  }) = WebSocketError_ProtocolError;

  /// An IO or transport-level failure occurred.
  const factory WebSocketError.transportError({
    required String message,
  }) = WebSocketError_TransportError;

  /// The peer closed the connection unexpectedly.
  const factory WebSocketError.connectionClosed({
    int? code,
    String? reason,
  }) = WebSocketError_ConnectionClosed;

  /// A local close was initiated.
  const factory WebSocketError.closedLocally() = WebSocketError_ClosedLocally;

  /// An unknown error occurred during WebSocket usage.
  const factory WebSocketError.unknown() = WebSocketError_Unknown;
}
