// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'http.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ClientSettings {
  final HttpVersionPref httpVersionPref;
  final Duration? timeout;
  final Duration? connectTimeout;

  const ClientSettings({
    required this.httpVersionPref,
    this.timeout,
    this.connectTimeout,
  });

  static Future<ClientSettings> default_() =>
      RustLib.instance.api.crateApiClientClientSettingsDefault();

  @override
  int get hashCode =>
      httpVersionPref.hashCode ^ timeout.hashCode ^ connectTimeout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientSettings &&
          runtimeType == other.runtimeType &&
          httpVersionPref == other.httpVersionPref &&
          timeout == other.timeout &&
          connectTimeout == other.connectTimeout;
}
